import Image from "next/image";
import { profile } from "@/content/profile";
import { projects } from "@/content/projects";
import { learningTopics } from "@/content/learning";
import { lifeEntries } from "@/content/life";
import { Reveal } from "./Reveal";

const world = [["Learn", "Things I’m trying to understand."], ["Build", "Things I’m trying to make."], ["Live", "Things worth remembering."]];
export function About() { return <Section id="about" number="02" label="About"><Reveal><h2 className="display max-w-3xl text-5xl leading-[.95] md:text-7xl">Hi, I’m jiejiejie.</h2><p className="mt-7 max-w-xl text-xl leading-relaxed text-[#686861]">{profile.intro}</p><p className="mt-12 max-w-2xl border-l border-[#a6a69e] pl-5 leading-relaxed text-[#686861]">{profile.about}</p></Reveal></Section> }
export function WorldCards() { return <Section id="world" number="03" label="My world"><div className="grid gap-3 md:grid-cols-3">{world.map(([title, desc], i) => <Reveal key={title} delay={i*.1}><article tabIndex={0} className="group min-h-72 rounded-[1.5rem] border rule p-7 transition duration-500 hover:-translate-y-1 hover:bg-[#e8ebe4] focus-visible:outline-2 focus-visible:outline-offset-4"><p className="text-5xl text-[#a9afa4]">0{i+1}</p><h3 className="display mt-20 text-4xl">{title}</h3><p className="mt-3 max-w-48 text-sm leading-relaxed text-[#686861]">{desc}</p></article></Reveal>)}</div></Section> }
export function RightNow() { return <Section id="now" number="04" label="Right now"><Reveal><div className="border-t rule">{profile.now.map(([label, value]) => <div className="grid gap-2 border-b rule py-5 md:grid-cols-[13rem_1fr]" key={label}><dt className="eyebrow">{label}</dt><dd className="text-lg tracking-[-.02em]">{value}</dd></div>)}</div></Reveal></Section> }
export function Projects() { const p = projects[0]; return <Section id="projects" number="05" label="Projects"><Reveal><article className="grid overflow-hidden rounded-[1.5rem] border rule md:grid-cols-2"><Image className="h-full min-h-72 w-full object-cover" src={p.image} width={1200} height={800} alt="Abstract placeholder representing AI Office Evaluation"/><div className="flex flex-col p-7 md:p-10"><p className="eyebrow">{p.date}</p><h3 className="display mt-12 text-5xl leading-none">{p.title}</h3><p className="mt-6 max-w-md leading-relaxed text-[#686861]">{p.description}</p><div className="mt-8 flex flex-wrap gap-2">{p.technologies.map(t => <span className="rounded-full border rule px-3 py-1 text-xs" key={t}>{t}</span>)}</div><a href={p.href} className="mt-10 inline-block text-sm underline decoration-[#aaa] underline-offset-4">View project <span aria-hidden>↗</span></a></div></article></Reveal></Section> }
export function LifeGallery() { return <Section id="life" number="06" label="Life"><div className="grid gap-8 md:grid-cols-3">{lifeEntries.map((entry,i) => <Reveal key={entry.image} delay={i*.1}><figure><Image className="aspect-[4/5] w-full rounded-[1.2rem] object-cover" src={entry.image} width={800} height={1000} alt={entry.caption}/><figcaption className="mt-4"><p className="text-sm">{entry.caption}</p><p className="mt-1 text-xs text-[#686861]">{entry.date} · {entry.location}</p></figcaption></figure></Reveal>)}</div></Section> }
export function Learning() { return <Section id="learning" number="07" label="Learning"><div className="grid gap-x-12 border-t rule md:grid-cols-2">{learningTopics.map((topic,i) => <Reveal key={topic.title} delay={i*.06}><article className="group flex items-start justify-between gap-4 border-b rule py-7"><div><h3 className="display text-3xl">{topic.title}</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-[#686861]">{topic.note}</p></div><span className="mt-2 text-xl transition-transform duration-300 group-hover:translate-x-1" aria-hidden>↗</span></article></Reveal>)}</div></Section> }
export function Contact() { return <Section id="contact" number="08" label="Contact"><Reveal><h2 className="display max-w-2xl text-5xl leading-[.95] md:text-7xl">Let’s keep in touch.</h2><div className="mt-12 flex flex-col items-start gap-4 text-xl md:text-2xl">{Object.entries(profile.contact).map(([key,value]) => <a className="underline decoration-[#b7b7b1] underline-offset-6 transition hover:decoration-black" key={key} href={key === "email" ? `mailto:${value}` : `https://${value}`} target={key === "email" ? undefined : "_blank"} rel="noreferrer">{key === "email" ? value : key[0].toUpperCase()+key.slice(1)}</a>)}</div></Reveal></Section> }
function Section({ id, number, label, children }: { id:string; number:string; label:string; children: React.ReactNode }) { return <section id={id} className="mx-auto max-w-7xl px-6 py-24 md:px-10 md:py-36"><header className="mb-13 flex items-center gap-4"><span className="eyebrow">{number}</span><span className="h-px w-10 bg-[#c8c8c1]"/><span className="eyebrow">{label}</span></header>{children}</section> }
