import Image from "next/image";
import { learningTopics } from "@/content/learning";
import { lifeEntries } from "@/content/life";
import { profile } from "@/content/profile";
import { projects } from "@/content/projects";
import { Reveal } from "./Reveal";

const world = [["Learn", "我正在学习和理解的东西"], ["Build", "我正在尝试制作的东西"], ["Live", "那些值得记录和珍惜的东西"]];

export function About() { return <Section id="about" number="02" label="About"><Reveal><h2 className="display max-w-4xl text-5xl leading-[.91] md:text-8xl">Hi, I’m {profile.name}.</h2><p className="mt-8 max-w-xl text-xl leading-relaxed tracking-[-.02em] text-[#60616d] md:text-2xl">{profile.intro}</p><p className="mt-14 max-w-2xl border-l border-[#bfc7d4] pl-6 text-[15px] leading-7 text-[#6c6e78]">{profile.about}</p></Reveal></Section> }

export function WorldCards() { return <Section id="world" number="03" label="My world"><div className="grid gap-4 md:grid-cols-3 items-stretch">{world.map(([title, desc], index) => <Reveal key={title} delay={index * .1} className="h-full"><article tabIndex={0} className="glass-panel group flex h-full min-h-80 flex-col rounded-[1.75rem] p-7 transition duration-500 hover:-translate-y-1 hover:bg-white/68 hover:shadow-[0_20px_50px_rgba(48,57,81,.1)] focus-visible:outline-2 focus-visible:outline-offset-4"><p className="text-sm text-[#a4aabc]">0{index + 1}</p><h3 className="display mt-24 text-5xl leading-none">{title}</h3><p className="mt-4 max-w-48 text-sm leading-relaxed text-[#6c6e78]">{desc}</p><span className="mt-auto pt-9 text-sm text-[#747a89] transition-transform duration-300 group-hover:translate-x-1" aria-hidden>↗</span></article></Reveal>)}</div></Section> }

export function RightNow() { return <Section id="now" number="04" label="Right now"><Reveal><dl className="glass-panel rounded-[1.6rem] px-6 md:px-10">{profile.now.map(([label, value]) => <div className="grid gap-2 border-b rule py-6 last:border-0 md:grid-cols-[14rem_1fr]" key={label}><dt className="eyebrow pt-1">{label}</dt><dd className="text-lg tracking-[-.025em] text-[#34353c]">{value}</dd></div>)}</dl></Reveal></Section> }

export function Projects() { const project = projects[0]; return <Section id="projects" number="05" label="Projects"><Reveal><article className="glass-panel grid overflow-hidden rounded-[1.9rem] md:grid-cols-2"><div className="relative min-h-78"><Image className="absolute inset-0 h-full w-full object-cover" src={project.image} width={1200} height={800} alt="Abstract placeholder representing AI Office Evaluation" /></div><div className="flex flex-col p-8 md:p-12"><p className="eyebrow">{project.date}</p><h3 className="display mt-14 text-5xl leading-[.88] md:text-6xl">{project.title}</h3><p className="mt-6 max-w-md leading-7 text-[#656773]">{project.description}</p><div className="mt-9 flex flex-wrap gap-2">{project.technologies.map((technology) => <span className="rounded-full border border-[#d6d9e2] bg-white/45 px-3 py-1 text-xs text-[#5e606a]" key={technology}>{technology}</span>)}</div><a href={project.href} className="mt-11 inline-block text-sm text-[#363841] underline decoration-[#b8c0cf] underline-offset-5 transition hover:decoration-[#363841]">View project <span aria-hidden>↗</span></a></div></article></Reveal></Section> }

export function LifeGallery() { return <Section id="life" number="06" label="Life"><div className="grid gap-8 md:grid-cols-3">{lifeEntries.map((entry, index) => <Reveal key={entry.image} delay={index * .1}><figure><div className="overflow-hidden rounded-[1.5rem] shadow-[0_15px_40px_rgba(57,62,79,.08)]"><Image className="aspect-[4/5] w-full object-cover transition duration-700 hover:scale-[1.025]" src={entry.image} width={800} height={1000} alt={entry.caption} /></div><figcaption className="mt-5"><p className="text-[15px] tracking-[-.01em]">{entry.caption}</p><p className="mt-1.5 text-xs text-[#747681]">{entry.date} · {entry.location}</p></figcaption></figure></Reveal>)}</div></Section> }

export function Learning() { return <Section id="learning" number="07" label="Learning"><div className="grid gap-x-14 md:grid-cols-2">{learningTopics.map((topic, index) => <Reveal key={topic.title} delay={index * .06}><article className="group flex items-start justify-between gap-4 border-t rule py-8 last:border-b"><div><h3 className="display text-4xl leading-none">{topic.title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-[#6b6d77]">{topic.note}</p></div><span className="mt-1 text-xl text-[#6c7483] transition-transform duration-300 group-hover:translate-x-1" aria-hidden>↗</span></article></Reveal>)}</div></Section> }

export function Contact() { return <Section id="contact" number="08" label="Contact"><Reveal><h2 className="display max-w-3xl text-5xl leading-[.9] md:text-8xl">Let’s keep in touch.</h2><div className="mt-13 flex flex-col items-start gap-5 text-xl tracking-[-.025em] md:text-2xl">{Object.entries(profile.contact).map(([key, value]) => <a className="text-[#4f515b] underline decoration-[#bdc5d2] underline-offset-7 transition hover:text-[#1d1d1f] hover:decoration-[#1d1d1f]" key={key} href={key === "email" ? `mailto:${value}` : `https://${value}`} target={key === "email" ? undefined : "_blank"} rel="noreferrer">{key === "email" ? value : key[0].toUpperCase() + key.slice(1)}</a>)}</div></Reveal></Section> }

function Section({ id, number, label, children }: { id: string; number: string; label: string; children: React.ReactNode }) { return <section id={id} className="relative mx-auto max-w-7xl px-6 py-25 md:px-10 md:py-40"><header className="mb-14 flex items-center gap-4"><span className="eyebrow">{number}</span><span className="h-px w-10 bg-[#c6ccd9]" /><span className="eyebrow">{label}</span></header>{children}</section> }
